export type Env = {
  DB: D1Database;
  BUCKET: R2Bucket;
  BROWSER?: Fetcher;
  REPORT_SCHEDULER: DurableObjectNamespace;
  ASSETS: Fetcher;
  SECRET_KEY: string;
  AI_BASE_URL?: string;
  AI_API_KEY?: string;
  ZHIPU_BASE_URL?: string;
  ZHIPU_API_KEY?: string;
  DEEPSEEK_BASE_URL?: string;
  DEEPSEEK_API_KEY?: string;
  AI_DEFAULT_MODEL?: string;
  AI_COMPLEX_MODEL?: string;
  AI_VISION_MODEL?: string;
  AI_STREAM_TIMEOUT_MS?: string;
  ADMIN_EMAIL?: string;
  ADMIN_INITIAL_PASSWORD?: string;
  APP_TIMEZONE: string;
  MAX_UPLOAD_BYTES: string;
};
